// src/contexts/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect } from 'react';

// Complete language configuration
export const languages = {
  en: {
    // Navigation
    dashboard: 'DASHBOARD',
    customers: 'CUSTOMERS',
    debts: 'DEBTS',
    payments: 'PAYMENTS',
    reports: 'REPORTS',
    settings: 'SETTINGS',
    logout: 'LOGOUT',
    
    // For customer 
    addCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',
    customer: 'Customer',
    customerList: 'Customer List',
    enterCustomerName: 'Enter customer name',
    enterEmailAddress: 'Enter email address',
    enterPhoneNumber: 'Enter phone number',
    enterAddress: 'Enter address',
    update: 'Update',
    save: 'Save',
    noCustomersFound: 'No customers found',
    addYourFirstCustomer: 'Add Your First Customer',
    addDebt: 'Add Debt',
    confirmDeleteCustomer: 'Are you sure you want to delete this customer?',
    
    // Dashboard
    availableBalance: 'Available Balance',
    seeDetails: 'See details',
    budgetFor: 'Budget for',
    cashAvailable: 'Cash Available',
    createSavingGoal: 'Create a Saving Goal',
    startSaving: 'Start saving for your future goals',
    enterAmount: 'Enter amount',
    cash: 'Cash',
    income: 'Income',
    mySpending: 'My Spending',
    recentTransactions: 'Recent Transactions',
    shopping: 'Shopping',
    restaurant: 'Restaurant',
    transport: 'Transport',
    uncategorized: 'Uncategorized',
    
    // Auth
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signInToManage: 'Sign in to manage your wealth',
    joinUs: 'Join us to start your financial journey',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email',
    enterPhone: 'Enter your phone number',
    enterPassword: 'Enter your password',
    confirmYourPassword: 'Confirm your password',
    dontHaveAccount: "Don't have an account? ",
    alreadyHaveAccount: "Already have an account? ",
    forgotPassword: 'Forgot your password?',
    passwordRecovery: 'Password Recovery',
    verifyCode: 'Verify Code',
    resetPassword: 'Reset Password',
    recoveryInstructions: 'Enter your email or phone to recover your account',
    enterVerificationCode: 'Enter the verification code sent to your phone/email',
    setNewPassword: 'Enter your new password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    sendCode: 'Send Code',
    resendCode: 'Resend Code',
    verify: 'Verify',
    cancel: 'Cancel',
    passwordsDontMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    invalidCredentials: 'Invalid credentials',
    userExists: 'User already exists',
    loginSuccessful: 'Login successful!',
    accountCreated: 'Account created successfully!',
    codeSent: 'Verification code sent! Check your phone or email.',
    codeVerified: 'Code verified! Please set your new password.',
    passwordReset: 'Password reset successfully! You can now login with your new password.',
    invalidCode: 'Invalid verification code',
    noAccountFound: 'No account found with this email or phone number',
    
    // Debts-specific translations
    debtsFor: 'Debts for',
    allDebts: 'All Debts',
    addDebt: 'Add Debt',
    editDebt: 'Edit Debt',
    addNewDebt: 'Add New Debt',
    debt: 'Debt',
    debtRecords: 'Debt Records',
    totalDebt: 'Total Debt',
    pendingAmount: 'Pending Amount',
    paidAmount: 'Paid Amount',
    pendingDebts: 'Pending Debts',
    enterDebtDescription: 'Enter debt description',
    products: 'Products',
    productName: 'Product name',
    quantity: 'Quantity',
    price: 'Price',
    addProduct: 'Add Product',
    totalAmount: 'Total Amount',
    noDebtRecordsFound: 'No debt records found',
    addYourFirstDebt: 'Add Your First Debt',
    selectCustomerFromCustomers: 'Select a customer from the Customers page to add debts',
    confirmDeleteDebt: 'Are you sure you want to delete this debt record?',
    markAsPaid: 'Mark as paid',
    noProductsListed: 'No products listed',
    unknownCustomer: 'Unknown Customer',
    noDescription: 'No description',
    pending: 'Pending',
    paid: 'Paid',
    overdue: 'Overdue',
    description: 'Description',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    
    // Payments-specific translations
    outstanding: 'Outstanding',
    totalPaid: 'Total Paid',
    filterDebts: 'Filter Debts',
    allCustomers: 'All Customers',
    allStatus: 'All Status',
    outstandingDebts: 'Outstanding Debts',
    noOutstandingDebtsFound: 'No outstanding debts found',
    makePayment: 'Make Payment',
    paymentSummary: 'Payment Summary',
    contact: 'Contact',
    outstandingBalance: 'Outstanding Balance',
    paymentAmount: 'Payment Amount',
    enterPaymentAmount: 'Enter payment amount',
    paymentDate: 'Payment Date',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    mobileMoney: 'Mobile Money',
    bankTransfer: 'Bank Transfer',
    card: 'Card',
    notes: 'Notes',
    optional: 'Optional',
    addPaymentNotes: 'Add any notes about this payment',
    paymentPreview: 'Payment Preview',
    amountToPay: 'Amount to Pay',
    remainingBalance: 'Remaining Balance',
    processPayment: 'Process Payment',
    sending: 'Sending',
    sendingPaymentConfirmation: 'Sending payment confirmation to customer...',
    recentPayments: 'Recent Payments',
    noPaymentsRecorded: 'No payments recorded yet',
    method: 'Method',
    completed: 'Completed',
    invalidPaymentAmount: 'Invalid payment amount',
    paymentSuccessful: 'Payment successful!',
    confirmationSentVia: 'Confirmation sent via',
    couldNotSendConfirmation: 'But could not send confirmation',
    noCustomerContactInfo: 'No customer contact information found for notification',
    errorSendingConfirmation: 'But there was an error sending the confirmation',
    notificationFailed: 'Notification failed',
    noContactInfo: 'No contact info',
    
    // Reports-specific translations
    financialReports: 'Financial Reports',
    reportType: 'Report Type',
    dailyReport: 'Daily Report',
    weeklyReport: 'Weekly Report',
    monthlyReport: 'Monthly Report',
    yearlyReport: 'Yearly Report',
    customRange: 'Custom Range',
    startDate: 'Start Date',
    endDate: 'End Date',
    generateReport: 'Generate Report',
    generatedOn: 'Generated on',
    totalRevenue: 'Total Revenue',
    totalDebts: 'Total Debts',
    totalCustomers: 'Total Customers',
    totalTransactions: 'Total Transactions',
    revenueVsDebts: 'Revenue vs Debts',
    revenue: 'Revenue',
    paymentMethods: 'Payment Methods',
    topCustomersByRevenue: 'Top Customers by Revenue',
    recentTransactions: 'Recent Transactions',
    generatedBy: 'Generated by',
    manageYourWealthWisely: 'Manage Your Wealth Wisely',
    page: 'Page',
    of: 'of',
    generatingReport: 'Generating report...',
    exportError: 'Error exporting report. Please try again.',
    selectReportTypeAndGenerate: 'Select report type and generate your first report',
    
    // Common
    companyName: 'CUNGA NEZA',
    tagline: 'TWIRINDE GUHOMBA',
    or: 'or',
    save: 'Save',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    loading: 'Loading',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    search: 'Search',
    filter: 'Filter'
  },
  rw: {
    // Navigation
    dashboard: 'AHABANZA',
    customers: 'ABAKIRIYA',
    debts: 'INGUZANYO',
    payments: 'IBISHYURWA',
    reports: 'RAPORO',
    settings: 'IGENAMITERERE',
    logout: 'SOHOKA',
    
    //customer
    addCustomer: 'Ongeramo Umukiriya',
    editCustomer: 'Hindura Umukiriya',
    customer: 'Umukiriya',
    customerList: 'Urutonde rw\'Abakiriya',
    enterCustomerName: 'Andika izina ry\'umukiriya',
    enterEmailAddress: 'Andika imeyili',
    enterPhoneNumber: 'Andika numero ya telefone',
    enterAddress: 'Andika aderesi',
    update: 'Hindura',
    save: 'Bika',
    noCustomersFound: 'Nta mukiriya wabonetse',
    addYourFirstCustomer: 'Ongeramo Umukiriya wawe wa Mbere',
    addDebt: 'Ongeramo Inguzanyo',
    confirmDeleteCustomer: 'Urabyizeye ko ushaka gusiba uyu mukiriya?',
      searchDebtsByCustomer: "Shakisha inguzanyo ku izina ry'umukiriya...",
  noDebtsMatchQuery: "Nta nguzanyo zihuye n'ibisabwa.",
    // Dashboard
    availableBalance: 'Amafaranga ahari',
    seeDetails: 'Reba ibisobanuro',
    budgetFor: 'Bajeti ya',
    cashAvailable: 'Amafaranga ahari',
    createSavingGoal: 'Kora Intego yo Kubika Amafaranga',
    startSaving: 'Tangira kubika ama faranga yawe kuzahora',
    enterAmount: 'Andika umubare',
    cash: 'Amafaranga',
    income: 'Amafaranga yinjira',
    mySpending: 'Amafaranga Nakoresha',
    recentTransactions: 'Ibikorwa Bigeze Bihise',
    shopping: 'Gura',
    restaurant: 'Uburiro',
    transport: 'Ubwikorezi',
    uncategorized: 'Bidashyizwe mu byiciro',
    
    // Auth
    welcomeBack: 'Murakaza neza',
    createAccount: 'Kora Konti',
    signIn: 'Injira',
    signUp: 'Iyandike',
    signInToManage: 'Injira kugirango woroshe uceceko kwawe',
    joinUs: 'Twiyunge hamwe gutangira urugendo rwawe rw\'imari',
    fullName: 'Amazina yuzuye',
    email: 'Imeyili',
    phone: 'Numero ya Telefone',
    password: 'Ijambobanga',
    confirmPassword: 'Emeza Ijambobanga',
    enterFullName: 'Andika amazina yawe yuzuye',
    enterEmail: 'Andika imeyili yawe',
    enterPhone: 'Andika numero ya telefone yawe',
    enterPassword: 'Andika ijambobanga ryawe',
    confirmYourPassword: 'Emeza ijambobanga ryawe',
    dontHaveAccount: 'Ntugira konti? ',
    alreadyHaveAccount: 'Urafite konti? ',
    forgotPassword: 'Wibagiwe ijambobanga?',
    passwordRecovery: 'Kuraho ijambobanga',
    verifyCode: 'Emeza Code',
    resetPassword: 'Shiraho ijambobanga rishya',
    recoveryInstructions: 'Andika imeyili cyangwa numero ya telefone kugirango ukureho konti yawe',
    enterVerificationCode: 'Andika code yo gusaba woherejwe kuri telefone/imeyili yawe',
    setNewPassword: 'Andika ijambobanga rishya',
    newPassword: 'Ijambobanga Rishya',
    confirmNewPassword: 'Emeza Ijambobanga Rishya',
    sendCode: 'Ohereza Code',
    resendCode: 'Ohereza Code nanone',
    verify: 'Emeza',
    cancel: 'Hagarika',
    passwordsDontMatch: 'Ijambobanga ntibihuye',
    passwordTooShort: 'Ijambobanga rigomba kuba rifite imibare 6 byibura',
    invalidCredentials: 'Amakuru atari yo',
    userExists: 'Uko konti iriho',
    loginSuccessful: 'Winjiye neza!',
    accountCreated: 'Konti yashizweho neza!',
    codeSent: 'Code yo gusaba yoherejwe! Reba kuri telefone cyangwa imeyili yawe.',
    codeVerified: 'Code yemejwe! Giba wshiraho ijambobanga rishya.',
    passwordReset: 'Ijambobanga ryasubiwemo neza! Ushobora noneho kwinjira ukoresheje ijambobanga rishya.',
    invalidCode: 'Code yo gusaba ntibikwiye',
    noAccountFound: 'Nta konti yabonetse ihuza iyi meyili cyangwa numero ya telefone',
    
    // Debts-specific translations
    debtsFor: 'Inguzanyo za',
    allDebts: 'Inguzanyo Zose',
    addDebt: 'Ongeramo Inguzanyo',
    editDebt: 'Hindura Inguzanyo',
    addNewDebt: 'Ongeramo Inguzanyo Nshya',
    debt: 'Inguzanyo',
    debtRecords: 'Amakuru y\'Inguzanyo',
    totalDebt: 'Inguzanyo yose',
    pendingAmount: 'Amafaranga Atarishyurwa',
    paidAmount: 'Amafaranga Yishyuwe',
    pendingDebts: 'Inguzanyo Itarishyurwa',
    enterDebtDescription: 'Andika ibisobanuro by\'inguzanyo',
    products: 'Ibicuruzwa',
    productName: 'Izina ry\'icuruzwa',
    quantity: 'Ingano',
    price: 'Igiciro',
    addProduct: 'Ongeramo Icuruzwa',
    totalAmount: 'Umubare Wose',
    noDebtRecordsFound: 'Nta makuru y\'inguzanyo abonetse',
    addYourFirstDebt: 'Ongeramo Inguzanyo yawe ya Mbere',
    selectCustomerFromCustomers: 'Hitamo umukiriya kuva kuri paje y\'Abakiriya kugirango wongeramo inguzanyo',
    confirmDeleteDebt: 'Urabyizeye ko ushaka gusiba iki kiringo cy\'inguzanyo?',
    markAsPaid: 'Shiraho nk\'ishyuwe',
    noProductsListed: 'Nta bicuruzwa byanditswe',
    unknownCustomer: 'Umukiriya Utazwi',
    noDescription: 'Nta bisobanuro',
    pending: 'Itarishyurwa',
    paid: 'Ishyura',
    overdue: 'Yarenze igihe',
    description: 'Ibisobanuro',
    date: 'Itariki',
    status: 'Imimerere',
    actions: 'Ibikorwa',
    edit: 'Hindura',
    delete: 'Siba',
    
    // Payments-specific translations
    outstanding: 'Itarishyurwa',
    totalPaid: 'Ayishyuwe yose',
    filterDebts: 'Tunganya Inguzanyo',
    allCustomers: 'Abakiriya Bose',
    allStatus: 'Imimerere Yose',
    outstandingDebts: 'Inguzanyo Itarishyurwa',
    noOutstandingDebtsFound: 'Nta nguzanyo itarishyurwa abonetse',
    makePayment: 'Shyura',
    paymentSummary: 'Incamake y\'Ishyurwa',
    contact: 'Uburyo bwo kuvugana',
    outstandingBalance: 'Amafaranga Atarishyurwa',
    paymentAmount: 'Umubare Wishyura',
    enterPaymentAmount: 'Andika umubare wishyura',
    paymentDate: 'Itariki yo Gushyura',
    paymentMethod: 'Uburyo bwo Gushyura',
    cash: 'Amafaranga',
    mobileMoney: 'Mobile Money',
    bankTransfer: 'Kohereza muri Banki',
    card: 'Ikarita',
    notes: 'Ibyanditswe',
    optional: 'Bihitamo',
    addPaymentNotes: 'Ongeramo ibyanditswe bijyanye n\'ishyurwa',
    paymentPreview: 'Ishusho y\'Ishyurwa',
    amountToPay: 'Umubare Wishyura',
    remainingBalance: 'Amafaranga Asigaye',
    processPayment: 'Kora Ishurwa',
    sending: 'Kohereza',
    sendingPaymentConfirmation: 'Kohereza uburishe bw\'ishyurwa kuri mukiriya...',
    recentPayments: 'Abamaze kwishyura',
    noPaymentsRecorded: 'Nta ishyurwa ryanditswe',
    method: 'Uburyo',
    completed: 'Byakozwe',
    invalidPaymentAmount: 'Umubare wishyura utemewe',
    paymentSuccessful: 'Ishyurwa ryakozwe neza!',
    confirmationSentVia: 'kwemeza  byoherejwe binyuze',
    couldNotSendConfirmation: 'Ariko ntibyakunze kohereza ibyemejwe',
    noCustomerContactInfo: 'Nta makuru yo kuvugana n\'umukiriya abonetse',
    errorSendingConfirmation: 'Ariko habaye ikosa mu kohereza uburishe',
    notificationFailed: 'Kohereza uburishe byanze',
    noContactInfo: 'Nta makuru yo kuvugana',
    
    // Reports-specific translations
    financialReports: 'Raporo y\'Imari',
    reportType: 'Ubwoko bwa Raporo',
    dailyReport: 'Raporo y\'Umunsi',
    weeklyReport: 'Raporo y\'Icyumweru',
    monthlyReport: 'Raporo y\'Ukwezi',
    yearlyReport: 'Raporo y\'Umwaka',
    customRange: 'Igihe Cyihariye',
    startDate: 'Itariki y\'Intangiriro',
    endDate: 'Itariki y\'Iherezo',
    generateReport: 'Kora Raporo',
    generatedOn: 'Yakozwe ku',
    totalRevenue: 'Amafaranga Yose Yinjira',
    totalDebts: 'Igiteranyo cyinguzanyo',
    totalCustomers: 'Abakiriya bose',
    totalTransactions: 'Ibikorwa Byose',
    revenueVsDebts: 'Amafaranga Yinjira vs Inguzanyo',
    revenue: 'Amafaranga Yinjira',
    paymentMethods: 'Uburyo bwo Gushyura',
    topCustomersByRevenue: 'Abakiriya Bera kuri Amafaranga Yinjira',
    recentTransactions: 'Ibikorwa Bigeze',
    generatedBy: 'Yakozwe na',
    manageYourWealthWisely: 'Kora uceceko kwawe mu buryo bwenge',
    page: 'Urupapuro',
    of: 'ya',
    generatingReport: 'Ikora raporo...',
    exportError: 'Ikosa mu soza raporo. Wongere ugerageze.',
    selectReportTypeAndGenerate: 'Hitamo ubwoko bwa raporo hanyuma ukore raporo yawe ya mbere',
    searchCustomersPlaceholder: "Shakisha abakiriya ku izina, imeyili, telefoni cyangwa aderesi...",
  noCustomersMatchQuery: "Nta bakiriya bahuye n'ibisabwa.",
  clearSearch: "Sukura amakuru",
    // Common
    companyName: 'CUNGA NEZA',
    tagline: 'TWIRINDE GUHOMBA',
    or: 'cyangwa',
    save: 'Bika',
    confirm: 'Emeza',
    back: 'Subira inyuma',
    next: 'Ibikurikira',
    loading: 'Iyegerana',
    error: 'Ikosa',
    success: 'Intsinzi',
    warning: 'Iburira',
    search: 'Shakisha',
    filter: 'Akayunguruzo'
  },
  fr: {
    // Navigation
    dashboard: 'TABLEAU DE BORD',
    customers: 'CLIENTS',
    debts: 'DETTES',
    payments: 'PAIEMENTS',
    reports: 'RAPPORTS',
    settings: 'PARAMÈTRES',
    logout: 'DÉCONNEXION',

    //customer
    addCustomer: 'Ajouter un Client',
    editCustomer: 'Modifier le Client',
    customer: 'Client',
    customerList: 'Liste des Clients',
    enterCustomerName: 'Entrez le nom du client',
    enterEmailAddress: 'Entrez l\'adresse email',
    enterPhoneNumber: 'Entrez le numéro de téléphone',
    enterAddress: 'Entrez l\'adresse',
    update: 'Mettre à jour',
    save: 'Enregistrer',
    noCustomersFound: 'Aucun client trouvé',
    addYourFirstCustomer: 'Ajouter Votre Premier Client',
    addDebt: 'Ajouter une Dette',
    confirmDeleteCustomer: 'Êtes-vous sûr de vouloir supprimer ce client?',
    
    // Dashboard
    availableBalance: 'Solde disponible',
    seeDetails: 'Voir les détails',
    budgetFor: 'Budget pour',
    cashAvailable: 'Argent disponible',
    createSavingGoal: 'Créer un objectif d\'épargne',
    startSaving: 'Commencez à épargner pour vos objectifs futurs',
    enterAmount: 'Entrez le montant',
    cash: 'Argent',
    income: 'Revenu',
    mySpending: 'Mes Dépenses',
    recentTransactions: 'Transactions Récentes',
    shopping: 'Shopping',
    restaurant: 'Restaurant',
    transport: 'Transport',
    uncategorized: 'Non catégorisé',
      searchDebtsByCustomer: "Rechercher des dettes par nom de client...",
  noDebtsMatchQuery: "Aucune dette ne correspond à vos critères de recherche.",
    // Auth
    welcomeBack: 'Bon retour',
    createAccount: 'Créer un compte',
    signIn: 'Se connecter',
    signUp: "S'inscrire",
    signInToManage: 'Connectez-vous pour gérer votre richesse',
    joinUs: 'Rejoignez-nous pour commencer votre voyage financier',
    fullName: 'Nom complet',
    email: 'E-mail',
    phone: 'Numéro de téléphone',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    enterFullName: 'Entrez votre nom complet',
    enterEmail: 'Entrez votre e-mail',
    enterPhone: 'Entrez votre numéro de téléphone',
    enterPassword: 'Entrez votre mot de passe',
    confirmYourPassword: 'Confirmez votre mot de passe',
    dontHaveAccount: "Vous n'avez pas de compte? ",
    alreadyHaveAccount: 'Vous avez déjà un compte? ',
    forgotPassword: 'Mot de passe oublié?',
    passwordRecovery: 'Récupération de mot de passe',
    verifyCode: 'Vérifier le code',
    resetPassword: 'Réinitialiser le mot de passe',
    recoveryInstructions: 'Entrez votre e-mail ou téléphone pour récupérer votre compte',
    enterVerificationCode: 'Entrez le code de vérification envoyé à votre téléphone/e-mail',
    setNewPassword: 'Entrez votre nouveau mot de passe',
    newPassword: 'Nouveau mot de passe',
    confirmNewPassword: 'Confirmer le nouveau mot de passe',
    sendCode: 'Envoyer le code',
    resendCode: 'Renvoyer le code',
    verify: 'Vérifier',
    cancel: 'Annuler',
    passwordsDontMatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Le mot de passe doit comporter au moins 6 caractères',
    invalidCredentials: 'Identifiants invalides',
    userExists: 'Utilisateur existe déjà',
    loginSuccessful: 'Connexion réussie!',
    accountCreated: 'Compte créé avec succès!',
    codeSent: 'Code de vérification envoyé! Vérifiez votre téléphone ou e-mail.',
    codeVerified: 'Code vérifié! Veuillez définir votre nouveau mot de passe.',
    passwordReset: 'Mot de passe réinitialisé avec succès! Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    invalidCode: 'Code de vérification invalide',
    noAccountFound: 'Aucun compte trouvé avec cet e-mail ou numéro de téléphone',
    
    // Debts-specific translations
    debtsFor: 'Dettes pour',
    allDebts: 'Toutes les Dettes',
    addDebt: 'Ajouter une Dette',
    editDebt: 'Modifier la Dette',
    addNewDebt: 'Ajouter une Nouvelle Dette',
    debt: 'Dette',
    debtRecords: 'Enregistrements de Dettes',
    totalDebt: 'Dette Totale',
    pendingAmount: 'Montant En Attente',
    paidAmount: 'Montant Payé',
    pendingDebts: 'Dettes En Attente',
    enterDebtDescription: 'Entrez la description de la dette',
    products: 'Produits',
    productName: 'Nom du produit',
    quantity: 'Quantité',
    price: 'Prix',
    addProduct: 'Ajouter un Produit',
    totalAmount: 'Montant Total',
    noDebtRecordsFound: 'Aucun enregistrement de dette trouvé',
    addYourFirstDebt: 'Ajouter Votre Première Dette',
    selectCustomerFromCustomers: 'Sélectionnez un client depuis la page Clients pour ajouter des dettes',
    confirmDeleteDebt: 'Êtes-vous sûr de vouloir supprimer cet enregistrement de dette?',
    markAsPaid: 'Marquer comme payé',
    noProductsListed: 'Aucun produit listé',
    unknownCustomer: 'Client Inconnu',
    noDescription: 'Aucune description',
    pending: 'En Attente',
    paid: 'Payé',
    overdue: 'En Retard',
    description: 'Description',
    date: 'Date',
    status: 'Statut',
    actions: 'Actions',
    edit: 'Modifier',
    delete: 'Supprimer',
    
    // Payments-specific translations
    outstanding: 'En Suspens',
    totalPaid: 'Total Payé',
    filterDebts: 'Filtrer les Dettes',
    allCustomers: 'Tous les Clients',
    allStatus: 'Tous les Statuts',
    outstandingDebts: 'Dettes En Suspens',
    noOutstandingDebtsFound: 'Aucune dette en suspens trouvée',
    makePayment: 'Effectuer un Paiement',
    paymentSummary: 'Résumé du Paiement',
    contact: 'Contact',
    outstandingBalance: 'Solde En Suspens',
    paymentAmount: 'Montant du Paiement',
    enterPaymentAmount: 'Entrez le montant du paiement',
    paymentDate: 'Date de Paiement',
    paymentMethod: 'Méthode de Paiement',
    cash: 'Espèces',
    mobileMoney: 'Mobile Money',
    bankTransfer: 'Virement Bancaire',
    card: 'Carte',
    notes: 'Notes',
    optional: 'Optionnel',
    addPaymentNotes: 'Ajoutez des notes concernant ce paiement',
    paymentPreview: 'Aperçu du Paiement',
    amountToPay: 'Montant à Payer',
    remainingBalance: 'Solde Restant',
    processPayment: 'Traiter le Paiement',
    sending: 'Envoi en cours',
    sendingPaymentConfirmation: 'Envoi de la confirmation de paiement au client...',
    recentPayments: 'Paiements Récents',
    noPaymentsRecorded: 'Aucun paiement enregistré',
    method: 'Méthode',
    completed: 'Terminé',
    invalidPaymentAmount: 'Montant de paiement invalide',
    paymentSuccessful: 'Paiement réussi!',
    confirmationSentVia: 'Confirmation envoyée via',
    couldNotSendConfirmation: 'Mais n\'a pas pu envoyer la confirmation',
    noCustomerContactInfo: 'Aucune information de contact client trouvée',
    errorSendingConfirmation: 'Mais il y a eu une erreur lors de l\'envoi de la confirmation',
    notificationFailed: 'Échec de la notification',
    noContactInfo: 'Aucune information de contact',
    
    // Reports-specific translations
    financialReports: 'Rapports Financiers',
    reportType: 'Type de Rapport',
    dailyReport: 'Rapport Quotidien',
    weeklyReport: 'Rapport Hebdomadaire',
    monthlyReport: 'Rapport Mensuel',
    yearlyReport: 'Rapport Annuel',
    customRange: 'Plage Personnalisée',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    generateReport: 'Générer le Rapport',
    generatedOn: 'Généré le',
    totalRevenue: 'Revenu Total',
    totalDebts: 'Dettes Totales',
    totalCustomers: 'Total des Clients',
    totalTransactions: 'Total des Transactions',
    revenueVsDebts: 'Revenu vs Dettes',
    revenue: 'Revenu',
    paymentMethods: 'Méthodes de Paiement',
    topCustomersByRevenue: 'Meilleurs Clients par Revenu',
    recentTransactions: 'Transactions Récentes',
    generatedBy: 'Généré par',
    manageYourWealthWisely: 'Gérez Votre Richesse Sagement',
    page: 'Page',
    of: 'sur',
    generatingReport: 'Génération du rapport...',
    exportError: 'Erreur lors de l\'exportation du rapport. Veuillez réessayer.',
    selectReportTypeAndGenerate: 'Sélectionnez le type de rapport et générez votre premier rapport',
    searchCustomersPlaceholder: "Search customers by name, email, phone or address...",
  noCustomersMatchQuery: "No customers match your search criteria.",
  clearSearch: "Clear search",
   searchCustomersPlaceholder: "Rechercher des clients par nom, email, téléphone ou adresse...",
  noCustomersMatchQuery: "Aucun client ne correspond à vos critères de recherche.",
  clearSearch: "Effacer la recherche",
    
    // Common
    companyName: 'CUNGA NEZA',
    tagline: 'TWIRINDE GUHOMBA',
    or: 'ou',
    save: 'Enregistrer',
    confirm: 'Confirmer',
    back: 'Retour',
    next: 'Suivant',
    loading: 'Chargement',
    error: 'Erreur',
    success: 'Succès',
    warning: 'Avertissement',
    search: 'Rechercher',
    filter: 'Filtrer'
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', currentLanguage);
  }, [currentLanguage]);

  const changeLanguage = (lang) => {
    if (languages[lang]) {
      setCurrentLanguage(lang);
    }
  };

  const t = languages[currentLanguage];

  return (
    <LanguageContext.Provider value={{ t, currentLanguage, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;